name: CI-CD

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: | 
            cividati/conversao-temperatura:latest
            cividati/conversao-temperatura:${{github.run_number}}