name: CI-CD

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: | 
            cividati/conversao-temperatura:latest
            cividati/conversao-temperatura:${{github.run_number}}
  
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
          context: <context name> # current-context from kubeconfig is used as default

      - uses: Azure/k8s-deploy@v3.1
        with:
          images: 'cividati/conversao-temperatura:${{ event.run_id }}'
          manifests: |
              manifest/deployment.yml